id: I41B3A819
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:57:09+00:00'
last_modified: '2022-06-08T03:09:32.591527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20198
  title: བཀའ་བརྒྱད་བདེ་བཤེགས་ཡོངས་འདུས་ཀྱི་བསྙེན་ཡིག་དོན་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    54C8:
      image_group_id: I8LS20200
      title: ''
      total_pages: 26
      order: 1
      base_file: 54C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
