id: P005448
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:51:04.605815
source_metadata:
  id: bdr:W8LS20198
  title: བཀའ་བརྒྱད་བདེ་བཤེགས་ཡོངས་འདུས་ཀྱི་བསྙེན་ཡིག་དོན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    34713c9e6f1947b796b611d1b2173af4:
      image_group_id: I8LS20200
      title: ''
      volume_number: 1
      total_pages: 26
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
